# Generated by Django 5.1.1 on 2025-09-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyReport',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='업체계약보고ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='보고일시')),
                ('noCompany', models.IntegerField(verbose_name='업체ID')),
                ('nType', models.IntegerField(choices=[(0, '가계약'), (1, '계약(입금X)'), (2, '계약(입금O)'), (3, '증액(입금X)'), (4, '증액(입금O)'), (5, '감액(환불X)'), (6, '감액(환불O)'), (7, '취소(환불X)'), (8, '취소(환불O)')], default=0, verbose_name='보고구분')),
                ('noPre', models.IntegerField(blank=True, null=True, verbose_name='관련 이전보고 ID')),
                ('noNext', models.IntegerField(blank=True, null=True, verbose_name='관련 이후보고 ID')),
                ('noConType', models.IntegerField(choices=[(0, '[카페건]인테리어/리모델링/기타'), (1, '[카테건]신축/증축/개축'), (2, '[소개건]인테리어/리모델링/기타'), (3, '[소개건]신축/증축/개축')], default=0, verbose_name='공사유형')),
                ('sPost', models.CharField(blank=True, max_length=200, verbose_name='게시글 번호')),
                ('noAssign', models.IntegerField(blank=True, null=True, verbose_name='할당ID')),
                ('sName', models.CharField(blank=True, max_length=50, verbose_name='고객 이름')),
                ('sPhone', models.CharField(blank=True, max_length=20, verbose_name='고객 핸드폰 번호')),
                ('sArea', models.TextField(blank=True, verbose_name='공사 주소')),
                ('dateContract', models.DateField(blank=True, null=True, verbose_name='공사 계약일')),
                ('dateSchedule', models.DateField(blank=True, null=True, verbose_name='공사 완료예정일')),
                ('nConMoney', models.IntegerField(default=0, verbose_name='공사 금액(원)')),
                ('bVat', models.BooleanField(default=False, verbose_name='vat포함 여부')),
                ('nFee', models.IntegerField(default=0, verbose_name='수수료(원)')),
                ('nAppPoint', models.IntegerField(default=0, verbose_name='적용포인트')),
                ('nDemand', models.IntegerField(default=0, verbose_name='청구액/환불액(원)')),
                ('dateDeposit', models.DateField(blank=True, null=True, verbose_name='입금일/환불일')),
                ('nDeposit', models.IntegerField(default=0, verbose_name='입금액/환불액')),
                ('nExcess', models.IntegerField(default=0, verbose_name='과/미입금(+ or -)')),
                ('nRefund', models.IntegerField(choices=[(0, '계좌이체'), (1, '포인트적립')], default=0, verbose_name='환불방식')),
                ('sCompanyName', models.CharField(blank=True, max_length=200, verbose_name='전자세금계산서 발행 사업자')),
                ('sAccount', models.CharField(blank=True, max_length=100, verbose_name='환불 통장계좌')),
                ('file', models.FileField(blank=True, null=True, upload_to='company_reports/', verbose_name='증빙자료')),
                ('sCompanyMemo', models.TextField(blank=True, verbose_name='남긴 말씀')),
                ('sStaffMemo', models.TextField(blank=True, verbose_name='메모')),
                ('sWorker', models.CharField(blank=True, max_length=50, verbose_name='보고자')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '업체계약보고',
                'verbose_name_plural': '업체계약보고',
                'db_table': 'company_report',
                'ordering': ['-no'],
            },
        ),
    ]
