# Generated by Django 5.1.1 on 2025-09-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientReport',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='고객계약보고ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='타임스탬프')),
                ('noCompany', models.IntegerField(verbose_name='업체 ID')),
                ('sCompanyName', models.CharField(blank=True, max_length=200, verbose_name='업체명')),
                ('sName', models.CharField(blank=True, max_length=50, verbose_name='고객 성함')),
                ('sPhone', models.CharField(blank=True, max_length=20, verbose_name='고객 핸드폰 번호')),
                ('sExplain', models.TextField(blank=True, verbose_name='소명 내용')),
                ('sPunish', models.TextField(blank=True, verbose_name='징계 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '고객계약보고',
                'verbose_name_plural': '고객계약보고',
                'db_table': 'client_report',
                'ordering': ['-no'],
            },
        ),
    ]
