# Generated by Django 4.2.17 on 2025-09-28 03:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_clientreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientreport',
            name='time',
        ),
        migrations.AddField(
            model_name='clientreport',
            name='dateContract',
            field=models.DateField(blank=True, null=True, verbose_name='공사계약일'),
        ),
        migrations.AddField(
            model_name='clientreport',
            name='dateExplain0',
            field=models.DateField(blank=True, null=True, verbose_name='소명요청 예정일'),
        ),
        migrations.AddField(
            model_name='clientreport',
            name='dateExplain1',
            field=models.DateField(blank=True, null=True, verbose_name='소명요청 실제일'),
        ),
        migrations.AddField(
            model_name='clientreport',
            name='nCheck',
            field=models.IntegerField(choices=[(0, '미확인'), (1, '불필요'), (2, '계약O'), (3, '계약X')], default=0, verbose_name='확인'),
        ),
        migrations.AddField(
            model_name='clientreport',
            name='noAssign',
            field=models.IntegerField(blank=True, null=True, verbose_name='할당ID'),
        ),
        migrations.AddField(
            model_name='clientreport',
            name='noCompanyReport',
            field=models.IntegerField(blank=True, null=True, verbose_name='업체계약보고ID'),
        ),
        migrations.AddField(
            model_name='clientreport',
            name='sArea',
            field=models.CharField(blank=True, max_length=200, verbose_name='공사지역'),
        ),
        migrations.AddField(
            model_name='clientreport',
            name='sClientMemo',
            field=models.TextField(blank=True, verbose_name='남긴 말씀'),
        ),
        migrations.AddField(
            model_name='clientreport',
            name='sConMoney',
            field=models.CharField(blank=True, max_length=50, verbose_name='공사금액(원)'),
        ),
        migrations.AddField(
            model_name='clientreport',
            name='sFile',
            field=models.TextField(blank=True, verbose_name='계약서 링크'),
        ),
        migrations.AddField(
            model_name='clientreport',
            name='sMemo',
            field=models.TextField(blank=True, verbose_name='메모'),
        ),
        migrations.AddField(
            model_name='clientreport',
            name='sPost',
            field=models.CharField(blank=True, max_length=200, verbose_name='게시글 링크'),
        ),
        migrations.AddField(
            model_name='clientreport',
            name='timeStamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='타임스탬프'),
        ),
        migrations.AlterField(
            model_name='clientreport',
            name='noCompany',
            field=models.IntegerField(verbose_name='업체ID'),
        ),
        migrations.AlterField(
            model_name='clientreport',
            name='sCompanyName',
            field=models.CharField(blank=True, max_length=200, verbose_name='업체명(구글)'),
        ),
        migrations.AlterField(
            model_name='clientreport',
            name='sName',
            field=models.CharField(blank=True, max_length=50, verbose_name='고객'),
        ),
        migrations.AlterField(
            model_name='clientreport',
            name='sPhone',
            field=models.CharField(blank=True, max_length=50, verbose_name='고객핸드폰'),
        ),
    ]
