# Generated by Django 4.2.17 on 2025-09-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_remove_clientreport_time_clientreport_datecontract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientreport',
            name='sDateContract',
            field=models.CharField(blank=True, max_length=50, verbose_name='공사계약일(구글)'),
        ),
        migrations.AddField(
            model_name='clientreport',
            name='sTimeStamp',
            field=models.CharField(blank=True, max_length=50, verbose_name='타임스탬프(구글)'),
        ),
        migrations.AlterField(
            model_name='clientreport',
            name='noCompany',
            field=models.IntegerField(default=0, verbose_name='업체ID'),
        ),
        migrations.AlterField(
            model_name='clientreport',
            name='timeStamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='타임스탬프'),
        ),
    ]
