# Generated by Django 4.2.17 on 2025-10-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_clientreport_sdatecontract_clientreport_stimestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyreport',
            name='time',
        ),
        migrations.AddField(
            model_name='companyreport',
            name='sConMoney',
            field=models.CharField(blank=True, max_length=50, verbose_name='공사금액(구글)'),
        ),
        migrations.AddField(
            model_name='companyreport',
            name='sDateContract',
            field=models.CharField(blank=True, max_length=50, verbose_name='공사계약일(구글)'),
        ),
        migrations.AddField(
            model_name='companyreport',
            name='sDateSchedule',
            field=models.CharField(blank=True, max_length=50, verbose_name='공사 완료예정일(구글)'),
        ),
        migrations.AddField(
            model_name='companyreport',
            name='sFile',
            field=models.TextField(blank=True, verbose_name='계약서 링크'),
        ),
        migrations.AddField(
            model_name='companyreport',
            name='sTaxCompany',
            field=models.CharField(blank=True, max_length=200, verbose_name='전자세금계산서 발행 사업자'),
        ),
        migrations.AddField(
            model_name='companyreport',
            name='sTimeStamp',
            field=models.CharField(blank=True, max_length=50, verbose_name='타임스탬프'),
        ),
        migrations.AddField(
            model_name='companyreport',
            name='timeStamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='타임스탬프'),
        ),
        migrations.AlterField(
            model_name='companyreport',
            name='dateContract',
            field=models.DateField(blank=True, null=True, verbose_name='공사계약일'),
        ),
        migrations.AlterField(
            model_name='companyreport',
            name='nConMoney',
            field=models.IntegerField(default=0, verbose_name='공사금액'),
        ),
        migrations.AlterField(
            model_name='companyreport',
            name='sArea',
            field=models.TextField(blank=True, verbose_name='공사지역'),
        ),
        migrations.AlterField(
            model_name='companyreport',
            name='sCompanyName',
            field=models.CharField(blank=True, max_length=200, verbose_name='업체명'),
        ),
        migrations.AlterField(
            model_name='companyreport',
            name='sName',
            field=models.CharField(blank=True, max_length=50, verbose_name='고객이름'),
        ),
        migrations.AlterField(
            model_name='companyreport',
            name='sPhone',
            field=models.CharField(blank=True, max_length=20, verbose_name='고객핸드폰'),
        ),
        migrations.AlterField(
            model_name='companyreport',
            name='sPost',
            field=models.CharField(blank=True, max_length=200, verbose_name='게시글 링크'),
        ),
    ]
