# Generated by Django 4.2.17 on 2025-10-14 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_remove_companyreport_time_companyreport_sconmoney_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyreport',
            name='bVat',
        ),
    ]
