# Generated by Django 4.2.17 on 2025-10-14 06:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_remove_companyreport_bvat'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreport',
            name='nPreConMoney',
            field=models.IntegerField(default=0, verbose_name='이전보고 공사금액'),
        ),
        migrations.AddField(
            model_name='companyreport',
            name='nPreFee',
            field=models.IntegerField(default=0, verbose_name='이전보고 수수료(원)'),
        ),
        migrations.AddField(
            model_name='companyreport',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='companyreport',
            name='nType',
            field=models.IntegerField(choices=[(0, '계약(입금X)'), (1, '계약(입금O)'), (2, '증액(입금X)'), (3, '증액(입금O)'), (4, '감액(환불X)'), (5, '감액(환불O)'), (6, '취소(환불X)'), (7, '취소(환불O)')], default=0, verbose_name='보고구분'),
        ),
    ]
