# Generated by Django 4.2.17 on 2025-10-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0007_companyreport_npreconmoney_companyreport_nprefee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreport',
            name='noOrder',
            field=models.IntegerField(blank=True, null=True, verbose_name='의뢰ID'),
        ),
        migrations.AlterField(
            model_name='companyreport',
            name='nType',
            field=models.IntegerField(choices=[(0, '계약(입금X)'), (1, '계약(입금O)'), (2, '증액(입금X)'), (3, '증액(입금O)'), (4, '감액(환불X)'), (5, '감액(환불O)'), (6, '취소(환불X)'), (7, '취소(환불O)'), (8, '수수료조정')], default=0, verbose_name='보고구분'),
        ),
    ]
