# Generated by Django 4.2.17 on 2025-10-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0008_companyreport_noorder_alter_companyreport_ntype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyreport',
            name='nType',
            field=models.IntegerField(choices=[(0, '계약(입금X)'), (1, '계약(입금O)'), (2, '증액(입금X)'), (3, '증액(입금O)'), (4, '감액(환불X)'), (5, '감액(환불O)'), (6, '취소(환불X)'), (7, '취소(환불O)')], default=0, verbose_name='보고구분'),
        ),
    ]
