# Generated by Django 4.2.17 on 2025-10-27 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0009_alter_companyreport_ntype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyreport',
            old_name='noConType',
            new_name='nConType',
        ),
    ]
