# Generated by Django 4.2.17 on 2025-10-31 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0010_rename_nocontype_to_ncontype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyReportFile',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='파일ID')),
                ('file', models.FileField(upload_to='company_report_files/%Y/%m/', verbose_name='파일')),
                ('original_name', models.CharField(max_length=255, verbose_name='원본 파일명')),
                ('file_size', models.IntegerField(verbose_name='파일 크기')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 시간')),
                ('uploaded_by', models.CharField(blank=True, max_length=50, verbose_name='업로드한 사람')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_files', to='contract.companyreport', verbose_name='계약보고')),
            ],
            options={
                'verbose_name': '업체계약보고 첨부파일',
                'verbose_name_plural': '업체계약보고 첨부파일',
                'db_table': 'company_report_file',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
