#!/bin/bash

echo "🔍 GitHub Actions 디버깅 스크립트"
echo "================================"
echo ""
echo "GitHub Secrets 재확인:"
echo ""
echo "1. https://github.com/park6711/testpark/settings/secrets/actions"
echo ""
echo "2. 다음 값이 정확한지 확인:"
echo "   - DOCKER_USERNAME = 7171man (따옴표 없이)"
echo "   - DOCKER_PASSWORD = dckr_pat_... (전체 토큰, 공백 없이)"
echo ""
echo "3. 일반적인 실수:"
echo "   ❌ 앞뒤 공백 포함"
echo "   ❌ 따옴표 포함"
echo "   ❌ 토큰 일부만 복사"
echo ""
echo "4. Secrets 수정 방법:"
echo "   - Secret 이름 클릭"
echo "   - Update 버튼 클릭"
echo "   - 새 값 입력 (공백 주의!)"
echo "   - Update secret 클릭"
echo ""
echo "5. 테스트 푸시 (빈 커밋):"
echo "   git commit --allow-empty -m 'test: GitHub Actions 재실행'"
echo "   git push origin master"