# Generated by Django 5.1.1 on 2025-09-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('no', models.AutoField(help_text='직원 번호', primary_key=True, serialize=False)),
                ('sNaverID0', models.TextField(help_text='네이버 ID (긴 텍스트)')),
                ('bApproval', models.BooleanField(default=False, help_text='승인 여부')),
                ('sNaverID', models.CharField(help_text='네이버 ID', max_length=255)),
                ('sName', models.CharField(help_text='이름', max_length=255)),
                ('sTeam', models.CharField(help_text='팀', max_length=255)),
                ('sTitle', models.CharField(help_text='직급', max_length=255)),
                ('sNick', models.CharField(help_text='닉네임', max_length=255)),
                ('sGoogleID', models.CharField(blank=True, help_text='구글 ID', max_length=255, null=True)),
                ('sPhone1', models.CharField(blank=True, help_text='전화번호1', max_length=255, null=True)),
                ('sPhone2', models.CharField(blank=True, help_text='전화번호2', max_length=255, null=True)),
                ('nMaster', models.IntegerField(choices=[(0, '일반'), (1, '마스터'), (2, '슈퍼마스터')], default=0, help_text='마스터 타입 (0:일반, 1:마스터, 2:슈퍼마스터)')),
                ('nStaffAuthority', models.IntegerField(choices=[(0, '권한없음'), (1, '읽기권한'), (2, '쓰기권한')], default=0, help_text='직원 권한 (0:권한없음, 1:읽기권한, 2:쓰기권한)')),
                ('nCompanyAuthority', models.IntegerField(choices=[(0, '권한없음'), (1, '읽기권한'), (2, '쓰기권한')], default=0, help_text='회사 권한 (0:권한없음, 1:읽기권한, 2:쓰기권한)')),
                ('nOrderAuthority', models.IntegerField(choices=[(0, '권한없음'), (1, '읽기권한'), (2, '쓰기권한')], default=0, help_text='주문 권한 (0:권한없음, 1:읽기권한, 2:쓰기권한)')),
                ('nContractAuthority', models.IntegerField(choices=[(0, '권한없음'), (1, '읽기권한'), (2, '쓰기권한')], default=0, help_text='계약 권한 (0:권한없음, 1:읽기권한, 2:쓰기권한)')),
                ('nEvaluationAuthority', models.IntegerField(choices=[(0, '권한없음'), (1, '읽기권한'), (2, '쓰기권한')], default=0, help_text='평가 권한 (0:권한없음, 1:읽기권한, 2:쓰기권한)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '직원',
                'verbose_name_plural': '직원들',
                'db_table': 'staff',
                'ordering': ['no'],
            },
        ),
    ]
