# Generated by Django 5.1.1 on 2025-09-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='sNaverID0',
            field=models.CharField(help_text='네이버 식별자', max_length=255),
        ),
    ]
