# Generated by Django 5.1.1 on 2025-09-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staff_snaverid0'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['no'], 'verbose_name': '스텝', 'verbose_name_plural': '스텝들'},
        ),
        migrations.AlterField(
            model_name='staff',
            name='nCompanyAuthority',
            field=models.IntegerField(choices=[(0, '권한없음'), (1, '읽기권한'), (2, '쓰기권한')], default=0, help_text='업체정보 권한 (0:권한없음, 1:읽기권한, 2:쓰기권한)'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='nContractAuthority',
            field=models.IntegerField(choices=[(0, '권한없음'), (1, '읽기권한'), (2, '쓰기권한')], default=0, help_text='계약관리 권한 (0:권한없음, 1:읽기권한, 2:쓰기권한)'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='nEvaluationAuthority',
            field=models.IntegerField(choices=[(0, '권한없음'), (1, '읽기권한'), (2, '쓰기권한')], default=0, help_text='업체평가 권한 (0:권한없음, 1:읽기권한, 2:쓰기권한)'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='nOrderAuthority',
            field=models.IntegerField(choices=[(0, '권한없음'), (1, '읽기권한'), (2, '쓰기권한')], default=0, help_text='의뢰할당 권한 (0:권한없음, 1:읽기권한, 2:쓰기권한)'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='nStaffAuthority',
            field=models.IntegerField(choices=[(0, '권한없음'), (1, '읽기권한'), (2, '쓰기권한')], default=0, help_text='스텝정보 권한 (0:권한없음, 1:읽기권한, 2:쓰기권한)'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='no',
            field=models.AutoField(help_text='No', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='sPhone1',
            field=models.CharField(blank=True, help_text='업무 핸드폰', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='sPhone2',
            field=models.CharField(blank=True, help_text='개인 핸드폰', max_length=255, null=True),
        ),
    ]
