# Generated by Django 5.1.1 on 2025-09-20 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImpossibleTerm',
            fields=[
                ('no', models.AutoField(help_text='공사불가능 기간 ID', primary_key=True, serialize=False)),
                ('noCompany', models.IntegerField(help_text='업체 ID')),
                ('time', models.DateTimeField(auto_now_add=True, help_text='입력일시')),
                ('dateStart', models.DateField(help_text='시작일')),
                ('dateEnd', models.DateField(blank=True, help_text='종료일', null=True)),
                ('sWorker', models.CharField(help_text='설정자', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일시')),
            ],
            options={
                'verbose_name': '공사불가능 기간',
                'verbose_name_plural': '공사불가능 기간',
                'db_table': 'impossibleterm',
                'ordering': ['-no'],
            },
        ),
    ]
