# Generated by Django 4.2.17 on 2025-10-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impossibleterm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impossibleterm',
            options={'ordering': ['-no'], 'verbose_name': '공사 불가능 기간', 'verbose_name_plural': '공사 불가능 기간'},
        ),
        migrations.AlterField(
            model_name='impossibleterm',
            name='no',
            field=models.AutoField(help_text='공사 불가능 기간 ID', primary_key=True, serialize=False),
        ),
    ]
