# Generated by Django 5.1.1 on 2025-09-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('no', models.AutoField(help_text='회원 번호', primary_key=True, serialize=False)),
                ('sNaverID0', models.CharField(blank=True, default='', help_text='네이버 식별자', max_length=255)),
                ('bApproval', models.BooleanField(default=False, help_text='승인 여부 (False: 미승인, True: 승인)')),
                ('sNaverID', models.CharField(help_text='네이버 이메일', max_length=255)),
                ('sCompanyName', models.CharField(help_text='업체명', max_length=100)),
                ('sName2', models.CharField(help_text='이름2', max_length=50)),
                ('noCompany', models.IntegerField(help_text='업체 번호')),
                ('sName', models.CharField(help_text='성명', max_length=50)),
                ('sPhone', models.CharField(blank=True, default='', help_text='연락처', max_length=20)),
                ('sCafeGrade', models.CharField(blank=True, default='', help_text='카페 등급', max_length=20)),
                ('nNick', models.CharField(blank=True, default='', help_text='별명', max_length=50)),
                ('bMaster', models.BooleanField(default=False, help_text='마스터 여부 (False: 일반, True: 마스터)')),
                ('nCompanyAuthority', models.IntegerField(choices=[(0, '권한없음'), (1, '읽기권한'), (2, '쓰기권한')], default=0, help_text='업체정보 권한')),
                ('nOrderAuthority', models.IntegerField(choices=[(0, '권한없음'), (1, '읽기권한'), (2, '쓰기권한')], default=0, help_text='의뢰할당 권한')),
                ('nContractAuthority', models.IntegerField(choices=[(0, '권한없음'), (1, '읽기권한'), (2, '쓰기권한')], default=0, help_text='계약관리 권한')),
                ('nEvaluationAuthority', models.IntegerField(choices=[(0, '권한없음'), (1, '읽기권한'), (2, '쓰기권한')], default=0, help_text='업체평가 권한')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일시')),
            ],
            options={
                'verbose_name': '회원',
                'verbose_name_plural': '회원',
                'db_table': 'member',
                'ordering': ['no'],
            },
        ),
    ]
