# Generated by Django 5.1.1 on 2025-09-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='sCafeGrade',
        ),
        migrations.AddField(
            model_name='member',
            name='nCafeGrade',
            field=models.IntegerField(choices=[(0, '일반'), (1, '광고제휴'), (2, '단종열린'), (3, '토탈열린'), (4, '연합회')], default=0, help_text='카페 등급'),
        ),
    ]
