# Generated by Django 5.1.1 on 2025-09-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_remove_member_scafegrade_member_ncafegrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='nDataAuthority',
            field=models.IntegerField(choices=[(0, '권한없음'), (1, '읽기권한'), (2, '쓰기권한')], default=0, help_text='데이터관리 권한'),
        ),
        migrations.AddField(
            model_name='member',
            name='nFinanceAuthority',
            field=models.IntegerField(choices=[(0, '권한없음'), (1, '읽기권한'), (2, '쓰기권한')], default=0, help_text='재무관리 권한'),
        ),
        migrations.AddField(
            model_name='member',
            name='nProjectAuthority',
            field=models.IntegerField(choices=[(0, '권한없음'), (1, '읽기권한'), (2, '쓰기권한')], default=0, help_text='프로젝트 권한'),
        ),
        migrations.AddField(
            model_name='member',
            name='nSalesAuthority',
            field=models.IntegerField(choices=[(0, '권한없음'), (1, '읽기권한'), (2, '쓰기권한')], default=0, help_text='영업관리 권한'),
        ),
        migrations.AddField(
            model_name='member',
            name='nStaffAuthority',
            field=models.IntegerField(choices=[(0, '권한없음'), (1, '읽기권한'), (2, '쓰기권한')], default=0, help_text='스텝관리 권한'),
        ),
        migrations.AddField(
            model_name='member',
            name='nSystemAuthority',
            field=models.IntegerField(choices=[(0, '권한없음'), (1, '읽기권한'), (2, '쓰기권한')], default=0, help_text='시스템관리 권한'),
        ),
    ]
