# Generated by Django 5.1.1 on 2025-09-18 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_member_ndataauthority_member_nfinanceauthority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='nFinanceAuthority',
        ),
        migrations.RemoveField(
            model_name='member',
            name='nProjectAuthority',
        ),
        migrations.RemoveField(
            model_name='member',
            name='nSalesAuthority',
        ),
        migrations.RemoveField(
            model_name='member',
            name='nStaffAuthority',
        ),
    ]
