# Generated by Django 5.1.1 on 2025-09-18 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_remove_member_nfinanceauthority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='nDataAuthority',
        ),
        migrations.RemoveField(
            model_name='member',
            name='nSystemAuthority',
        ),
    ]
