# Generated by Django 5.1.1 on 2025-09-19 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_remove_member_ndataauthority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='bMaster',
        ),
    ]
