# Generated by Django 5.1.1 on 2025-09-17 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authsession',
            name='login_type',
            field=models.CharField(choices=[('normal', '일반 로그인'), ('staff', '스텝 로그인')], default='normal', help_text='로그인 타입', max_length=10),
        ),
        migrations.AddField(
            model_name='authsession',
            name='staff_email',
            field=models.CharField(blank=True, help_text='스텝 이메일 (스텝 로그인)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='authsession',
            name='user',
            field=models.ForeignKey(blank=True, help_text='연결된 사용자 (일반 로그인)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
