# Generated by Django 5.1.1 on 2025-09-21 09:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0006_company_datestopend_company_datestopstart_and_more'),
        ('contract', '0002_clientreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='포인트내역ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='타임스탬프')),
                ('nType', models.IntegerField(choices=[(0, '기타'), (1, '취소환불액'), (2, '과/미입금'), (3, '페이백 적립'), (4, '닷컴포인트 전환'), (5, '포인트 소멸')], default=0, verbose_name='구분')),
                ('sWorker', models.CharField(blank=True, max_length=50, verbose_name='작업자')),
                ('nPrePoint', models.IntegerField(default=0, verbose_name='이전 포인트')),
                ('nUsePoint', models.IntegerField(default=0, verbose_name='사용 포인트')),
                ('nRemainPoint', models.IntegerField(default=0, verbose_name='잔액 포인트')),
                ('sMemo', models.TextField(blank=True, verbose_name='메모')),
                ('noCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_records', to='company.company', verbose_name='업체ID')),
                ('noCompanyReport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_records', to='contract.companyreport', verbose_name='업체계약보고ID')),
            ],
            options={
                'verbose_name': '포인트',
                'verbose_name_plural': '포인트',
                'db_table': 'point',
                'ordering': ['-time', '-no'],
            },
        ),
    ]
