# Generated by Django 5.1.1 on 2025-09-23 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_datestopend_company_datestopstart_and_more'),
        ('point', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='noCompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='point_records', to='company.company', verbose_name='업체ID'),
        ),
    ]
