# Generated by Django 4.2.17 on 2025-09-23 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_datestopend_company_datestopstart_and_more'),
        ('point', '0002_change_company_deletion_to_protect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='noCompany',
            field=models.ForeignKey(blank=True, db_column='noCompany', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_records', to='company.company', verbose_name='업체ID'),
        ),
    ]
