# Generated by Django 4.2.17 on 2025-10-14 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_remove_companyreport_bvat'),
        ('point', '0003_alter_point_nocompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='nType',
            field=models.IntegerField(choices=[(0, '수수료 납부'), (1, '수수료 환불'), (2, '과/미입금'), (3, '페이백 적립'), (4, '닷컴포인트 전환')], default=0, verbose_name='구분'),
        ),
        migrations.AlterField(
            model_name='point',
            name='nUsePoint',
            field=models.IntegerField(default=0, verbose_name='적용 포인트'),
        ),
        migrations.AlterField(
            model_name='point',
            name='noCompanyReport',
            field=models.ForeignKey(blank=True, db_column='noCompanyReport', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_records', to='contract.companyreport', verbose_name='계약보고ID'),
        ),
    ]
