# Generated by Django 4.2.17 on 2025-10-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0004_alter_point_ntype_alter_point_nusepoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='noCompany',
            field=models.IntegerField(blank=True, db_column='noCompany', null=True, verbose_name='업체ID'),
        ),
    ]
