# Generated by Django 4.2.17 on 2025-10-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0005_convert_nocompany_to_intfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='noCompanyReport',
            field=models.IntegerField(blank=True, db_column='noCompanyReport', null=True, verbose_name='계약보고ID'),
        ),
    ]
