# Generated by Django 5.1.1 on 2025-09-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('no', models.AutoField(help_text='지역 ID', primary_key=True, serialize=False)),
                ('sState', models.CharField(help_text='광역지역명', max_length=50)),
                ('sCity', models.CharField(help_text='시군구지역명', max_length=50)),
            ],
            options={
                'verbose_name': '지역',
                'verbose_name_plural': '지역',
                'db_table': 'area',
                'ordering': ['sState', 'sCity'],
            },
        ),
    ]
