# Generated by Django 4.2.17 on 2025-10-14 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['no'], 'verbose_name': '지역', 'verbose_name_plural': '지역'},
        ),
    ]
