# Generated by Django 5.1.1 on 2025-09-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='템프리트ID')),
                ('nType', models.IntegerField(choices=[(0, '문자'), (1, '댓글')], default=0, verbose_name='분류')),
                ('nSort', models.IntegerField(choices=[(0, '기타'), (1, '의뢰할당'), (2, '업체관리'), (3, '업체평가'), (4, '계약회계')], default=0, verbose_name='분류2')),
                ('nReceiver', models.IntegerField(choices=[(0, '기타'), (1, '업체'), (2, '고객')], default=0, verbose_name='수신 대상')),
                ('sTitle', models.CharField(blank=True, max_length=200, verbose_name='제목')),
                ('sContent', models.TextField(verbose_name='내용')),
                ('nUse', models.IntegerField(default=0, verbose_name='사용횟수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '템플리트',
                'verbose_name_plural': '템플리트',
                'db_table': 'template',
                'ordering': ['-no'],
            },
        ),
    ]
