# Generated by Django 5.1.1 on 2025-09-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='nSort',
        ),
        migrations.AlterField(
            model_name='template',
            name='nType',
            field=models.IntegerField(choices=[(0, '기타'), (1, '문자'), (2, '의뢰할당'), (3, '업체관리'), (4, '업체평가'), (5, '계약회계')], default=0, verbose_name='분류'),
        ),
    ]
