# Generated by Django 4.2.17 on 2025-09-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0002_remove_template_nsort_alter_template_ntype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='nReceiver',
            field=models.IntegerField(choices=[(0, '기타'), (1, '업체'), (2, '고객')], default=0, help_text='0:기타, 1:업체, 2:고객', verbose_name='수신대상'),
        ),
        migrations.AlterField(
            model_name='template',
            name='nType',
            field=models.IntegerField(choices=[(0, '문자'), (1, '댓글')], default=0, help_text='0:문자, 1:댓글', verbose_name='구분'),
        ),
        migrations.AlterField(
            model_name='template',
            name='no',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='템플리트ID'),
        ),
        migrations.AlterField(
            model_name='template',
            name='sTitle',
            field=models.CharField(max_length=100, verbose_name='제목'),
        ),
    ]
