# Generated by Django 4.2.17 on 2025-10-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0003_alter_template_nreceiver_alter_template_ntype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='nReceiver',
            field=models.IntegerField(choices=[(0, '기타'), (1, '업체'), (2, '고객')], default=0, verbose_name='수신대상'),
        ),
        migrations.AlterField(
            model_name='template',
            name='nType',
            field=models.IntegerField(choices=[(0, '문자'), (1, '댓글')], default=0, verbose_name='구분'),
        ),
    ]
