# Generated by Django 5.1.1 on 2025-09-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('sName1', models.CharField(max_length=100, verbose_name='이름1')),
                ('sName2', models.CharField(blank=True, max_length=100, verbose_name='이름2')),
                ('sName3', models.CharField(blank=True, max_length=100, verbose_name='이름3')),
                ('sNaverID', models.CharField(blank=True, max_length=50, verbose_name='네이버 ID')),
                ('nType', models.IntegerField(choices=[(0, '일반토탈'), (1, '고정비토탈'), (2, '부분단종'), (3, '순수단종'), (4, 'btoc제휴'), (5, 'btob제휴')], default=0, verbose_name='업체 타입')),
                ('nCondition', models.IntegerField(choices=[(0, '준비중'), (1, '정상'), (2, '일시정지'), (3, '탈퇴')], default=0, verbose_name='업체 상태')),
                ('sCompanyName', models.CharField(max_length=200, verbose_name='업체명')),
                ('sAddress', models.TextField(verbose_name='주소')),
                ('nMember', models.IntegerField(default=0, verbose_name='회원수')),
                ('sBuildLicense', models.CharField(blank=True, max_length=100, verbose_name='건설면허')),
                ('fileBuildLicense', models.FileField(blank=True, null=True, upload_to='build_licenses/', verbose_name='건설면허 파일')),
                ('sStrength', models.TextField(blank=True, verbose_name='강점')),
                ('sCeoName', models.CharField(blank=True, max_length=50, verbose_name='대표자명')),
                ('sCeoPhone', models.CharField(blank=True, max_length=20, verbose_name='대표자 연락처')),
                ('sCeoMail', models.EmailField(blank=True, max_length=254, verbose_name='대표자 이메일')),
                ('fileCeo', models.FileField(blank=True, null=True, upload_to='ceo_files/', verbose_name='대표자 파일')),
                ('sSaleName', models.CharField(blank=True, max_length=50, verbose_name='영업담당자명')),
                ('sSalePhone', models.CharField(blank=True, max_length=20, verbose_name='영업담당자 연락처')),
                ('sSaleMail', models.EmailField(blank=True, max_length=254, verbose_name='영업담당자 이메일')),
                ('fileSale', models.FileField(blank=True, null=True, upload_to='sale_files/', verbose_name='영업담당자 파일')),
                ('sAccoutName', models.CharField(blank=True, max_length=50, verbose_name='정산담당자명')),
                ('sAccoutPhone', models.CharField(blank=True, max_length=20, verbose_name='정산담당자 연락처')),
                ('sAccoutMail', models.EmailField(blank=True, max_length=254, verbose_name='정산담당자 이메일')),
                ('fileLicense', models.FileField(blank=True, null=True, upload_to='license_files/', verbose_name='면허 파일')),
                ('sEmergencyName', models.CharField(blank=True, max_length=50, verbose_name='비상연락처명')),
                ('sEmergencyPhone', models.CharField(blank=True, max_length=20, verbose_name='비상연락처')),
                ('sEmergencyRelation', models.CharField(blank=True, max_length=50, verbose_name='비상연락처 관계')),
                ('dateJoin', models.DateField(blank=True, null=True, verbose_name='가입일')),
                ('nJoinFee', models.IntegerField(default=0, verbose_name='가입비(원)')),
                ('nDeposit', models.IntegerField(default=0, verbose_name='보증금(원)')),
                ('nFixFee', models.IntegerField(default=0, verbose_name='고정비(원)')),
                ('dateFixFeeStart', models.DateField(blank=True, null=True, verbose_name='고정비 시작일')),
                ('nFeePercent', models.FloatField(default=0.0, verbose_name='수수료율')),
                ('nOrderFee', models.IntegerField(default=0, verbose_name='주문수수료(원)')),
                ('nReportPeriod', models.IntegerField(default=0, verbose_name='보고주기')),
                ('fileContract', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='계약서 파일들')),
                ('fileCampaignAgree', models.FileField(blank=True, null=True, upload_to='campaign_agrees/', verbose_name='캠페인 동의서')),
                ('bPrivacy', models.BooleanField(default=False, verbose_name='개인정보동의')),
                ('bCompetition', models.BooleanField(default=False, verbose_name='경쟁업체')),
                ('bAptAll', models.BooleanField(default=False, verbose_name='아파트 전체')),
                ('bAptPart', models.BooleanField(default=False, verbose_name='아파트 부분')),
                ('bHouseAll', models.BooleanField(default=False, verbose_name='주택 전체')),
                ('bHousePart', models.BooleanField(default=False, verbose_name='주택 부분')),
                ('bCommerceAll', models.BooleanField(default=False, verbose_name='상업시설 전체')),
                ('bCommercePart', models.BooleanField(default=False, verbose_name='상업시설 부분')),
                ('bBuild', models.BooleanField(default=False, verbose_name='신축')),
                ('bExtra', models.BooleanField(default=False, verbose_name='기타')),
                ('bUnion', models.BooleanField(default=False, verbose_name='연합회')),
                ('bMentor', models.BooleanField(default=False, verbose_name='멘토')),
                ('sMentee', models.CharField(blank=True, max_length=100, verbose_name='멘티')),
                ('nRefund', models.IntegerField(choices=[(0, '계좌이체'), (1, '포인트적립')], default=0, verbose_name='환불방식')),
                ('sManager', models.CharField(blank=True, max_length=50, verbose_name='담당자')),
                ('dateWithdraw', models.DateField(blank=True, null=True, verbose_name='탈퇴일')),
                ('sWithdraw', models.CharField(blank=True, max_length=200, verbose_name='탈퇴사유')),
                ('sMemo', models.TextField(blank=True, verbose_name='메모')),
                ('sPicture', models.CharField(blank=True, max_length=200, verbose_name='사진')),
                ('sGallery', models.TextField(blank=True, verbose_name='갤러리')),
                ('sEstimate', models.TextField(blank=True, verbose_name='견적서')),
            ],
            options={
                'verbose_name': '업체',
                'verbose_name_plural': '업체',
                'db_table': 'company',
            },
        ),
    ]
