# Generated by Django 5.1.1 on 2025-09-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='bAptAll',
            field=models.BooleanField(default=False, verbose_name='아파트 올수리'),
        ),
        migrations.AlterField(
            model_name='company',
            name='bBuild',
            field=models.BooleanField(default=False, verbose_name='신축/증축'),
        ),
        migrations.AlterField(
            model_name='company',
            name='bCommerceAll',
            field=models.BooleanField(default=False, verbose_name='상업시설 올수리'),
        ),
        migrations.AlterField(
            model_name='company',
            name='bCompetition',
            field=models.BooleanField(default=False, verbose_name='경업동의'),
        ),
        migrations.AlterField(
            model_name='company',
            name='bExtra',
            field=models.BooleanField(default=False, verbose_name='부가서비스'),
        ),
        migrations.AlterField(
            model_name='company',
            name='bHouseAll',
            field=models.BooleanField(default=False, verbose_name='주택 올수리'),
        ),
        migrations.AlterField(
            model_name='company',
            name='fileContract',
            field=models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='협약서 파일들'),
        ),
        migrations.AlterField(
            model_name='company',
            name='nMember',
            field=models.IntegerField(default=0, verbose_name='직원수'),
        ),
        migrations.AlterField(
            model_name='company',
            name='nOrderFee',
            field=models.IntegerField(default=0, verbose_name='오더당 수수료(원)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='nRefund',
            field=models.IntegerField(choices=[(0, '계좌이체'), (1, '포인트적립')], default=0, verbose_name='선호 환불방식'),
        ),
        migrations.AlterField(
            model_name='company',
            name='sAccoutMail',
            field=models.EmailField(blank=True, max_length=254, verbose_name='회계담당자 이메일'),
        ),
        migrations.AlterField(
            model_name='company',
            name='sAccoutName',
            field=models.CharField(blank=True, max_length=50, verbose_name='회계담당자명'),
        ),
        migrations.AlterField(
            model_name='company',
            name='sAccoutPhone',
            field=models.CharField(blank=True, max_length=20, verbose_name='회계담당자 연락처'),
        ),
        migrations.AlterField(
            model_name='company',
            name='sEstimate',
            field=models.TextField(blank=True, verbose_name='견적방'),
        ),
        migrations.AlterField(
            model_name='company',
            name='sGallery',
            field=models.TextField(blank=True, verbose_name='갤러리방'),
        ),
        migrations.AlterField(
            model_name='company',
            name='sManager',
            field=models.CharField(blank=True, max_length=50, verbose_name='담당 스텝'),
        ),
        migrations.AlterField(
            model_name='company',
            name='sName1',
            field=models.CharField(max_length=100, verbose_name='열린업체명1'),
        ),
        migrations.AlterField(
            model_name='company',
            name='sName2',
            field=models.CharField(blank=True, max_length=100, verbose_name='열린업체명2'),
        ),
        migrations.AlterField(
            model_name='company',
            name='sName3',
            field=models.CharField(blank=True, max_length=100, verbose_name='열린업체명3'),
        ),
        migrations.AlterField(
            model_name='company',
            name='sPicture',
            field=models.CharField(blank=True, max_length=200, verbose_name='업체사진'),
        ),
    ]
