# Generated by Django 5.1.1 on 2025-09-18 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_baptall_alter_company_bbuild_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='fileContract',
        ),
        migrations.AlterField(
            model_name='company',
            name='bCompetition',
            field=models.BooleanField(default=False, verbose_name='경업금지동의'),
        ),
        migrations.AlterField(
            model_name='company',
            name='fileBuildLicense',
            field=models.FileField(blank=True, null=True, upload_to='build_licenses/', verbose_name='건설면허 사진'),
        ),
        migrations.AlterField(
            model_name='company',
            name='fileCeo',
            field=models.FileField(blank=True, null=True, upload_to='ceo_files/', verbose_name='대표자 사진'),
        ),
        migrations.AlterField(
            model_name='company',
            name='fileLicense',
            field=models.FileField(blank=True, null=True, upload_to='license_files/', verbose_name='사업자등록증 사진'),
        ),
        migrations.AlterField(
            model_name='company',
            name='fileSale',
            field=models.FileField(blank=True, null=True, upload_to='sale_files/', verbose_name='영업담당자 사진'),
        ),
        migrations.CreateModel(
            name='ContractFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='contracts/', verbose_name='협약서 사진')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='파일명')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 일시')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_files', to='company.company', verbose_name='업체')),
            ],
            options={
                'verbose_name': '협약서 파일',
                'verbose_name_plural': '협약서 파일들',
                'db_table': 'company_contract_file',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
