# Generated by Django 5.1.1 on 2025-09-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_company_filecontract_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='nFeePercent',
            new_name='fFeePercent',
        ),
        migrations.AlterField(
            model_name='company',
            name='bAptPart',
            field=models.BooleanField(default=False, verbose_name='아파트 부분수리'),
        ),
        migrations.AlterField(
            model_name='company',
            name='bCommercePart',
            field=models.BooleanField(default=False, verbose_name='상가 부분수리'),
        ),
        migrations.AlterField(
            model_name='company',
            name='bHousePart',
            field=models.BooleanField(default=False, verbose_name='주택 부분수리'),
        ),
        migrations.AlterField(
            model_name='company',
            name='fileCampaignAgree',
            field=models.FileField(blank=True, null=True, upload_to='campaign_agrees/', verbose_name='계약 및 하자이행보증증권 발행 캠페인 참여동의서'),
        ),
        migrations.AlterField(
            model_name='company',
            name='sBuildLicense',
            field=models.CharField(blank=True, max_length=100, verbose_name='보유 건설면허'),
        ),
        migrations.AlterField(
            model_name='company',
            name='sStrength',
            field=models.TextField(blank=True, verbose_name='업체 특장점'),
        ),
    ]
