# Generated by Django 5.1.1 on 2025-09-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_rename_nfeepercent_company_ffeepercent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='noLicenseRepresent',
            field=models.IntegerField(blank=True, null=True, verbose_name='대표 라이센스 번호'),
        ),
        migrations.AddField(
            model_name='company',
            name='noMemberMaster',
            field=models.IntegerField(blank=True, null=True, verbose_name='마스터 멤버 번호'),
        ),
    ]
