# Generated by Django 5.1.1 on 2025-09-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_company_nolicenserepresent_company_nomembermaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='dateStopEnd',
            field=models.DateField(blank=True, null=True, verbose_name='일시정지 종료일'),
        ),
        migrations.AddField(
            model_name='company',
            name='dateStopStart',
            field=models.DateField(blank=True, null=True, verbose_name='일시정지 시작일'),
        ),
        migrations.AddField(
            model_name='company',
            name='fAssignLack',
            field=models.FloatField(default=0.0, verbose_name='고정비업체 할당부족개수'),
        ),
        migrations.AddField(
            model_name='company',
            name='fAssignPercent',
            field=models.FloatField(default=0.0, verbose_name='할당퍼센트'),
        ),
        migrations.AddField(
            model_name='company',
            name='nApplyGrade',
            field=models.IntegerField(default=0, verbose_name='적용등급'),
        ),
        migrations.AddField(
            model_name='company',
            name='nAssignAll2',
            field=models.IntegerField(default=0, verbose_name='올수리 2일 할당수'),
        ),
        migrations.AddField(
            model_name='company',
            name='nAssignAllTerm',
            field=models.IntegerField(default=0, verbose_name='올수리 평가기간 할당수'),
        ),
        migrations.AddField(
            model_name='company',
            name='nAssignMax',
            field=models.IntegerField(default=0, verbose_name='최대할당수'),
        ),
        migrations.AddField(
            model_name='company',
            name='nAssignPart2',
            field=models.IntegerField(default=0, verbose_name='부분수리 2일 할당수'),
        ),
        migrations.AddField(
            model_name='company',
            name='nAssignPartTerm',
            field=models.IntegerField(default=0, verbose_name='부분수리 평가기간 할당수'),
        ),
        migrations.AddField(
            model_name='company',
            name='nGrade',
            field=models.IntegerField(default=0, verbose_name='현재등급'),
        ),
        migrations.AddField(
            model_name='company',
            name='nLevel',
            field=models.IntegerField(default=0, verbose_name='현재레벨'),
        ),
        migrations.AddField(
            model_name='company',
            name='sApplyGradeReason',
            field=models.CharField(blank=True, max_length=200, verbose_name='적용등급 사유'),
        ),
        migrations.AddField(
            model_name='company',
            name='sStop',
            field=models.TextField(blank=True, verbose_name='일시정지 사유'),
        ),
    ]
