# Generated by Django 5.1.1 on 2025-09-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gonggu',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='공동구매ID')),
                ('nStepType', models.IntegerField(choices=[(0, '준비중'), (1, '진행중'), (3, '일시정지'), (4, '마감')], default=0, verbose_name='진행구분')),
                ('nType', models.IntegerField(choices=[(0, '올수리'), (1, '부분/기타')], default=0, verbose_name='구분')),
                ('sNo', models.CharField(blank=True, max_length=50, verbose_name='공구회차')),
                ('dateStart', models.DateField(blank=True, null=True, verbose_name='시작일')),
                ('dateEnd', models.DateField(blank=True, null=True, verbose_name='마감일')),
                ('sName', models.TextField(blank=True, verbose_name='공구이름')),
                ('sPost', models.CharField(blank=True, max_length=200, verbose_name='공지글')),
                ('sStrength', models.TextField(blank=True, verbose_name='특징')),
                ('nCommentPre', models.IntegerField(default=0, verbose_name='네이버 이전 댓글수')),
                ('nCommentNow', models.IntegerField(default=0, verbose_name='네이버 현재 댓글수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '공동구매',
                'verbose_name_plural': '공동구매',
                'db_table': 'gonggu',
                'ordering': ['-no'],
            },
        ),
    ]
