# Generated by Django 5.1.1 on 2025-09-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gonggu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GongguArea',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='공구가능지역ID')),
                ('noGonggu', models.IntegerField(verbose_name='공동구매ID')),
                ('noCompany', models.IntegerField(verbose_name='업체ID')),
                ('nType', models.IntegerField(choices=[(0, '추가지역'), (1, '제외지역'), (2, '실제할당지역')], default=0, verbose_name='보관형식')),
                ('noArea', models.IntegerField(verbose_name='지역ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '공구가능지역',
                'verbose_name_plural': '공구가능지역',
                'db_table': 'gonggu_area',
                'ordering': ['-no'],
                'unique_together': {('noGonggu', 'noCompany', 'noArea')},
            },
        ),
    ]
