# Generated by Django 5.1.1 on 2025-09-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gonggu', '0002_gongguarea'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gongguarea',
            unique_together={('noGonggu', 'noArea')},
        ),
        migrations.AddField(
            model_name='gonggu',
            name='noCompany',
            field=models.IntegerField(blank=True, null=True, verbose_name='참여업체'),
        ),
        migrations.AlterField(
            model_name='gonggu',
            name='nStepType',
            field=models.IntegerField(choices=[(0, '준비중'), (1, '진행중'), (2, '일시정지'), (3, '마감')], default=0, verbose_name='진행구분'),
        ),
        migrations.RemoveField(
            model_name='gongguarea',
            name='noCompany',
        ),
    ]
