# Generated by Django 5.1.1 on 2025-09-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gonggu', '0003_alter_gongguarea_unique_together_gonggu_nocompany_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gongguarea',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='gonggu',
            name='noCompany',
        ),
        migrations.AddField(
            model_name='gongguarea',
            name='noGongguCompany',
            field=models.IntegerField(blank=True, null=True, verbose_name='공구업체ID'),
        ),
        migrations.CreateModel(
            name='GongguCompany',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='공구업체ID')),
                ('noGonggu', models.IntegerField(verbose_name='공동구매ID')),
                ('noCompany', models.IntegerField(verbose_name='업체ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '공구업체',
                'verbose_name_plural': '공구업체',
                'db_table': 'gonggu_company',
                'ordering': ['-no'],
                'unique_together': {('noGonggu', 'noCompany')},
            },
        ),
        migrations.RemoveField(
            model_name='gongguarea',
            name='noGonggu',
        ),
    ]
