# Generated by Django 4.2.17 on 2025-09-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalVar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='변수명')),
                ('value', models.TextField(verbose_name='값')),
                ('var_type', models.CharField(choices=[('int', '정수'), ('float', '실수'), ('str', '문자열'), ('bool', '불린')], default='str', max_length=10, verbose_name='타입')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('category', models.CharField(default='EVALUATION', max_length=50, verbose_name='카테고리')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '전역변수',
                'verbose_name_plural': '전역변수',
                'db_table': 'global_vars',
                'ordering': ['category', 'key'],
            },
        ),
    ]
