# Generated by Django 5.1.1 on 2025-09-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='의뢰ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='타임스탬프')),
                ('sAppoint', models.CharField(blank=True, max_length=100, verbose_name='업체공구지정')),
                ('sNick', models.CharField(blank=True, max_length=50, verbose_name='별명')),
                ('sNaverID', models.CharField(blank=True, max_length=50, verbose_name='네이버 ID')),
                ('sName', models.CharField(blank=True, max_length=50, verbose_name='성명')),
                ('sPhone', models.CharField(blank=True, max_length=20, verbose_name='고객 핸드폰')),
                ('sPost', models.CharField(blank=True, max_length=200, verbose_name='의뢰게시글')),
                ('sArea', models.TextField(blank=True, verbose_name='공사지역')),
                ('dateSchedule', models.DateField(blank=True, null=True, verbose_name='공사예정일')),
                ('sConstruction', models.TextField(blank=True, verbose_name='공사내용')),
                ('bPrivacy1', models.BooleanField(default=False, verbose_name='개인정보 동의')),
                ('bPrivacy2', models.BooleanField(default=False, verbose_name='3자제공 동의')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '의뢰',
                'verbose_name_plural': '의뢰',
                'db_table': 'order',
                'ordering': ['-no'],
            },
        ),
    ]
