# Generated by Django 5.1.1 on 2025-09-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='할당ID')),
                ('noOrder', models.IntegerField(verbose_name='의뢰ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='타임스탬프')),
                ('noCompany', models.IntegerField(verbose_name='업체ID')),
                ('nConstructionType', models.IntegerField(choices=[(0, '아파트 올수리'), (1, '아파트 부분수리'), (2, '주택 올수리'), (3, '주택 부분수리'), (4, '상가 올수리'), (5, '상가 부분수리'), (6, '신축/증축'), (7, '부가서비스')], default=0, verbose_name='공사종류')),
                ('nAssignType', models.IntegerField(choices=[(0, '대기중'), (1, '할당'), (2, '반려'), (3, '취소'), (4, '제외'), (5, '업체미비'), (6, '중복접수'), (7, '가능문의'), (8, '불가능답변')], default=0, verbose_name='할당상태')),
                ('sCompanyPhone', models.CharField(blank=True, max_length=20, verbose_name='업체폰번호')),
                ('sCompanySMS', models.TextField(blank=True, verbose_name='업체 문자멘트')),
                ('sClientPhone', models.CharField(blank=True, max_length=20, verbose_name='고객폰번호')),
                ('sClientSMS', models.TextField(blank=True, verbose_name='고객문자멘트')),
                ('sWorker', models.CharField(blank=True, max_length=50, verbose_name='작업자')),
                ('noCompanyReport', models.IntegerField(blank=True, null=True, verbose_name='업체계약보고ID')),
                ('nAppoint', models.IntegerField(choices=[(0, '지정없음'), (1, '업체지정'), (2, '공구지정')], default=0, verbose_name='지정종류')),
                ('noGonggu', models.IntegerField(blank=True, null=True, verbose_name='공구ID')),
                ('noArea', models.IntegerField(blank=True, null=True, verbose_name='지역ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '할당',
                'verbose_name_plural': '할당',
                'db_table': 'assign',
                'ordering': ['-no'],
            },
        ),
    ]
