# Generated by Django 5.1.1 on 2025-09-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_assign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='할당견적ID')),
                ('noOrder', models.IntegerField(verbose_name='의뢰ID')),
                ('noAssign', models.IntegerField(verbose_name='할당ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='타임스탬프')),
                ('sPost', models.CharField(blank=True, max_length=200, verbose_name='견적서 게시글')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '할당견적',
                'verbose_name_plural': '할당견적',
                'db_table': 'estimate',
                'ordering': ['-no'],
            },
        ),
    ]
