# Generated by Django 5.1.1 on 2025-09-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_estimate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignMemo',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='할당메모ID')),
                ('noOrder', models.IntegerField(verbose_name='의뢰ID')),
                ('noAssign', models.IntegerField(verbose_name='할당ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='타임스탬프')),
                ('sWorker', models.CharField(blank=True, max_length=50, verbose_name='작업자')),
                ('sMemo', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '할당메모',
                'verbose_name_plural': '할당메모',
                'db_table': 'assign_memo',
                'ordering': ['-no'],
            },
        ),
    ]
