# Generated by Django 4.2.24 on 2025-09-22 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_datestopend_company_datestopstart_and_more'),
        ('order', '0004_assignmemo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='템플릿ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='템플릿명')),
                ('content', models.TextField(verbose_name='템플릿내용')),
                ('variables', models.JSONField(default=list, help_text='예: ["name", "workContent"]', verbose_name='변수목록')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': '메시지템플릿',
                'verbose_name_plural': '메시지템플릿',
                'db_table': 'message_template',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_company',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='할당업체명'),
        ),
        migrations.AddField(
            model_name='order',
            name='designation',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='지정'),
        ),
        migrations.AddField(
            model_name='order',
            name='designation_type',
            field=models.CharField(choices=[('지정없음', '지정없음'), ('업체지정', '업체지정'), ('공동구매', '공동구매')], default='지정없음', max_length=20, verbose_name='지정타입'),
        ),
        migrations.AddField(
            model_name='order',
            name='post_link',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='의뢰게시글 링크'),
        ),
        migrations.AddField(
            model_name='order',
            name='re_request_count',
            field=models.IntegerField(default=0, verbose_name='재의뢰횟수'),
        ),
        migrations.AddField(
            model_name='order',
            name='recent_status',
            field=models.CharField(choices=[('대기중', '대기중'), ('할당', '할당'), ('반려', '반려'), ('취소', '취소'), ('제외', '제외'), ('업체미비', '업체미비'), ('중복접수', '중복접수'), ('연락처오류', '연락처오류'), ('가능문의', '가능문의'), ('불가능답변(X)', '불가능답변(X)'), ('고객문의', '고객문의'), ('계약', '계약')], default='대기중', max_length=30, verbose_name='최근할당상태'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='접수일시'),
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='상태이력ID')),
                ('old_status', models.CharField(max_length=30, verbose_name='이전상태')),
                ('new_status', models.CharField(max_length=30, verbose_name='새상태')),
                ('message_sent', models.BooleanField(default=False, verbose_name='문자발송여부')),
                ('message_content', models.TextField(blank=True, verbose_name='문자내용')),
                ('author', models.CharField(max_length=50, verbose_name='작업자')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='변경일시')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_histories', to='order.order', verbose_name='의뢰')),
            ],
            options={
                'verbose_name': '상태변경이력',
                'verbose_name_plural': '상태변경이력',
                'db_table': 'status_history',
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='QuoteLink',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='견적링크ID')),
                ('open_quote_link', models.URLField(blank=True, max_length=500, verbose_name='공개견적서링크')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_links', to='order.order', verbose_name='의뢰')),
            ],
            options={
                'verbose_name': '견적링크',
                'verbose_name_plural': '견적링크',
                'db_table': 'quote_link',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteDraft',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='초안ID')),
                ('draft_type', models.CharField(choices=[('1차', '1차'), ('2차', '2차'), ('3차', '3차'), ('4차', '4차'), ('5차', '5차'), ('최종', '최종')], max_length=10, verbose_name='초안타입')),
                ('link', models.URLField(max_length=500, verbose_name='링크')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('quote_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='order.quotelink', verbose_name='견적링크')),
            ],
            options={
                'verbose_name': '견적초안',
                'verbose_name_plural': '견적초안',
                'db_table': 'quote_draft',
                'ordering': ['datetime'],
            },
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='메모ID')),
                ('author', models.CharField(max_length=50, verbose_name='작성자')),
                ('content', models.TextField(verbose_name='내용')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos', to='order.order', verbose_name='의뢰')),
            ],
            options={
                'verbose_name': '메모',
                'verbose_name_plural': '메모',
                'db_table': 'memo',
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='GroupPurchase',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='공동구매ID')),
                ('round', models.CharField(max_length=20, verbose_name='회차')),
                ('company_name', models.CharField(max_length=100, verbose_name='업체명')),
                ('unavailable_dates', models.JSONField(default=list, verbose_name='불가능날짜들')),
                ('available_areas', models.JSONField(default=list, verbose_name='가능지역들')),
                ('name', models.CharField(max_length=100, verbose_name='공동구매명')),
                ('link', models.URLField(blank=True, max_length=500, verbose_name='링크')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company', verbose_name='업체')),
            ],
            options={
                'verbose_name': '공동구매',
                'verbose_name_plural': '공동구매',
                'db_table': 'group_purchase',
                'ordering': ['-round'],
            },
        ),
        migrations.CreateModel(
            name='ChangeHistory',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='변경이력ID')),
                ('field_name', models.CharField(max_length=50, verbose_name='필드명')),
                ('field_label', models.CharField(max_length=50, verbose_name='필드라벨')),
                ('old_value', models.TextField(blank=True, verbose_name='이전값')),
                ('new_value', models.TextField(blank=True, verbose_name='새값')),
                ('author', models.CharField(max_length=50, verbose_name='작업자')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='변경일시')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_histories', to='order.order', verbose_name='의뢰')),
            ],
            options={
                'verbose_name': '변경이력',
                'verbose_name_plural': '변경이력',
                'db_table': 'change_history',
                'ordering': ['-datetime'],
            },
        ),
    ]
