# Generated by Django 4.2.24 on 2025-09-24 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_messagetemplate_order_assigned_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='google_sheet_uuid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='구글 시트 UUID'),
        ),
    ]
