# Generated by Django 4.2.17 on 2025-10-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='dateEnd',
            field=models.DateField(blank=True, help_text='종료일', null=True),
        ),
    ]
