# Generated by Django 5.1.1 on 2025-09-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PossibleArea',
            fields=[
                ('no', models.AutoField(help_text='공사 가능 지역 ID', primary_key=True, serialize=False)),
                ('noCompany', models.IntegerField(help_text='업체 ID')),
                ('nAreaType', models.IntegerField(choices=[(0, '추가지역'), (1, '업체제외지역'), (2, '스텝제외지역'), (3, '업체요청지역'), (4, '실제할당지역'), (5, '광역가능지역')], help_text='보관형식')),
                ('nConstructionType', models.IntegerField(choices=[(0, '올수리'), (1, '부분수리'), (2, '신축/증축'), (3, '부가서비스')], help_text='공사종류')),
                ('noArea', models.IntegerField(help_text='지역 ID')),
            ],
            options={
                'verbose_name': '공사 가능 지역',
                'verbose_name_plural': '공사 가능 지역',
                'db_table': 'possiblearea',
                'ordering': ['noCompany', 'nAreaType', 'nConstructionType'],
            },
        ),
    ]
