# Generated by Django 5.1.1 on 2025-09-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('no', models.AutoField(help_text='사업자 번호', primary_key=True, serialize=False)),
                ('noCompany', models.IntegerField(help_text='업체 번호')),
                ('sCompanyName', models.CharField(help_text='업체명', max_length=100)),
                ('sLicenseNo', models.CharField(help_text='사업자등록번호', max_length=50)),
                ('sCeoName', models.CharField(help_text='대표자명', max_length=50)),
                ('sAccountMail', models.CharField(help_text='계좌 메일', max_length=100)),
                ('fileLicense', models.FileField(blank=True, help_text='사업자등록증 파일', null=True, upload_to='license/license_files/')),
                ('sAccount', models.CharField(help_text='계좌번호', max_length=100)),
                ('fileAccount', models.FileField(blank=True, help_text='통장사본 파일', null=True, upload_to='license/account_files/')),
                ('bRepresent', models.BooleanField(default=False, help_text='대표 여부 (False: 일반, True: 대표)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일시')),
            ],
            options={
                'verbose_name': '사업자',
                'verbose_name_plural': '사업자',
                'db_table': 'license',
                'ordering': ['no'],
            },
        ),
    ]
