# Generated by Django 5.1.1 on 2025-09-19 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='bRepresent',
        ),
    ]
